huggingFace_token = "HUGGING_FACE_TOKEN_HERE"

CHATGPT_APIKEY= "CHAT_GPT_APIKEY_HERE"
NEWS_API_KEY = "NEWS_API_KEY_HERE"

BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN_HERE"
BOT_USERNAME = "@BOT_USERNAME_HERE"

NASA_API = "NASA_API_HERE"
